//
//  DeckViewEntityConstant.swift
//  yugioh
//
//  Created by Aaron on 9/8/2017.
//  Copyright © 2017 sightcorner. All rights reserved.
//

import Foundation


var deckViewEntitysConstant: [DeckViewEntity] = [
    DeckViewEntity(id: "100", title: "我的卡组", introduction: "我的卡组", deckEntitys: []),
    DeckViewEntity(id: "2005",
                   title: "2005年第3届冠军",
                   introduction: "使用时间：2005年8月7日 使用地点：日本东京 使用者：Markou Miltiadis 所属国家地区：希腊 卡组类型：【变异混沌凤凰神】",
                   deckEntitys: [
                    DeckEntity(id: "895", number: 1),
                    DeckEntity(id: "1501", number: 1),
                    DeckEntity(id: "91", number: 1),
                    DeckEntity(id: "366", number: 1),
                    DeckEntity(id: "607", number: 1),
                    DeckEntity(id: "1133", number: 1),
                    DeckEntity(id: "806", number: 1),
                    DeckEntity(id: "811", number: 1),
                    DeckEntity(id: "868", number: 1),
                    DeckEntity(id: "917", number: 1),
                    DeckEntity(id: "416", number: 1),
                    DeckEntity(id: "520", number: 1),
                    DeckEntity(id: "1502", number: 1),
                    DeckEntity(id: "801", number: 1),
                    DeckEntity(id: "260", number: 2),
                    DeckEntity(id: "1158", number: 1),
                    DeckEntity(id: "220", number: 1),
                    DeckEntity(id: "504", number: 1),
                    DeckEntity(id: "124", number: 1),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "37", number: 1),
                    DeckEntity(id: "127", number: 1),
                    DeckEntity(id: "26", number: 1),
                    DeckEntity(id: "1610", number: 1),
                    DeckEntity(id: "1098", number: 1),
                    DeckEntity(id: "29", number: 1),
                    DeckEntity(id: "662", number: 2),
                    DeckEntity(id: "207", number: 1),
                    DeckEntity(id: "717", number: 2),
                    DeckEntity(id: "1226", number: 2),
                    DeckEntity(id: "524", number: 1),
                    DeckEntity(id: "1171", number: 1),
                    DeckEntity(id: "101", number: 1),
                    DeckEntity(id: "474", number: 1),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "626", number: 1)
        ]),
    DeckViewEntity(id: "2004",
               title: "2004年第2届冠军",
               introduction: "使用时间：2004年7月25日 使用地点：美国洛杉矶 使用者：Togawa Masatoshi 所属国家地区：日本卡 组类型：【混沌Control】",
               deckEntitys: [
                DeckEntity(id: "1004", number: 1),
                DeckEntity(id: "973", number: 1),
                DeckEntity(id: "91", number: 1),
                DeckEntity(id: "366", number: 2),
                DeckEntity(id: "806", number: 1),
                DeckEntity(id: "811", number: 1),
                DeckEntity(id: "868", number: 3),
                DeckEntity(id: "73", number: 1),
                DeckEntity(id: "454", number: 1),
                DeckEntity(id: "416", number: 1),
                DeckEntity(id: "260", number: 1),
                DeckEntity(id: "808", number: 1),
                DeckEntity(id: "1158", number: 1),
                DeckEntity(id: "220", number: 1),
                DeckEntity(id: "504", number: 1),
                DeckEntity(id: "663", number: 1),
                DeckEntity(id: "171", number: 1),
                DeckEntity(id: "1043", number: 1),
                DeckEntity(id: "124", number: 1),
                DeckEntity(id: "478", number: 1),
                DeckEntity(id: "37", number: 3),
                DeckEntity(id: "26", number: 1),
                DeckEntity(id: "615", number: 1),
                DeckEntity(id: "219", number: 1),
                DeckEntity(id: "127", number: 1),
                DeckEntity(id: "28", number: 1),
                DeckEntity(id: "35", number: 1),
                DeckEntity(id: "1226", number: 2),
                DeckEntity(id: "474", number: 1),
                DeckEntity(id: "335", number: 2),
                DeckEntity(id: "1171", number: 1),
                DeckEntity(id: "101", number: 1)
        ]),
    DeckViewEntity(id: "2003",
               title: "2003年第1届冠军",
               introduction: "使用时间：2003年8月10日 使用地点：美国纽约 使用者：Ng Yu Leung 所属国家地区：中国香港 卡组类型：【手札破坏】",
               deckEntitys: [
                DeckEntity(id: "91", number: 1),
                DeckEntity(id: "498", number: 3),
                DeckEntity(id: "366", number: 1),
                DeckEntity(id: "657", number: 2),
                DeckEntity(id: "79", number: 3),
                DeckEntity(id: "454", number: 1),
                DeckEntity(id: "416", number: 1),
                DeckEntity(id: "590", number: 1),
                DeckEntity(id: "260", number: 1),
                DeckEntity(id: "1158", number: 1),
                DeckEntity(id: "601", number: 1),
                DeckEntity(id: "220", number: 1),
                DeckEntity(id: "504", number: 1),
                DeckEntity(id: "663", number: 1),
                DeckEntity(id: "172", number: 1),
                DeckEntity(id: "171", number: 1),
                DeckEntity(id: "124", number: 1),
                DeckEntity(id: "1149", number: 1),
                DeckEntity(id: "478", number: 1),
                DeckEntity(id: "37", number: 3),
                DeckEntity(id: "272", number: 1),
                DeckEntity(id: "26", number: 1),
                DeckEntity(id: "219", number: 1),
                DeckEntity(id: "127", number: 1),
                DeckEntity(id: "28", number: 1),
                DeckEntity(id: "35", number: 1),
                DeckEntity(id: "29", number: 1),
                DeckEntity(id: "122", number: 1),
                DeckEntity(id: "474", number: 1),
                DeckEntity(id: "1171", number: 1),
                DeckEntity(id: "101", number: 1),
                DeckEntity(id: "631", number: 3)
        ])

]
