//
//  DeckViewEntityConstant.swift
//  yugioh
//
//  Created by Aaron on 9/8/2017.
//  Copyright © 2017 sightcorner. All rights reserved.
//

import Foundation



var deckViewEntitysConstant: [DeckViewEntity] = [
    DeckViewEntity(id: "0", title: "我的卡组", introduction: "我的卡组", deckEntitys: [String: [DeckEntity]]()),
    DeckViewEntity(id: "forbid",
                   title: "2018年4月OCG禁止卡",
                   introduction: "2018年4月OCG禁止卡，不能出现在卡组里",
                   deckEntitys: ["0": [
                    DeckEntity(id: "8155", number: 1),
                    DeckEntity(id: "8009", number: 1),
                    DeckEntity(id: "8007", number: 1),
                    DeckEntity(id: "7761", number: 1),
                    DeckEntity(id: "7327", number: 1),
                    DeckEntity(id: "7214", number: 1),
                    DeckEntity(id: "7201", number: 1),
                    DeckEntity(id: "6996", number: 1),
                    DeckEntity(id: "6940", number: 1),
                    DeckEntity(id: "6554", number: 1),
                    DeckEntity(id: "5792", number: 1),
                    DeckEntity(id: "5791", number: 1),
                    DeckEntity(id: "5790", number: 1),
                    DeckEntity(id: "5789", number: 1),
                    DeckEntity(id: "5114", number: 1),
                    DeckEntity(id: "5080", number: 1),
                    DeckEntity(id: "5005", number: 1),
                    DeckEntity(id: "4147", number: 1),
                    DeckEntity(id: "3890", number: 1),
                    DeckEntity(id: "3798", number: 1),
                    DeckEntity(id: "3785", number: 1),
                    DeckEntity(id: "3627", number: 1),
                    DeckEntity(id: "3228", number: 1),
                    DeckEntity(id: "3098", number: 1),
                    DeckEntity(id: "1243", number: 1),
                    DeckEntity(id: "808", number: 1),
                    DeckEntity(id: "601", number: 1),
                    DeckEntity(id: "590", number: 1),
                    DeckEntity(id: "138", number: 1),
                    DeckEntity(id: "62", number: 1),
                    DeckEntity(id: "8184", number: 1),
                    DeckEntity(id: "8015", number: 1),
                    DeckEntity(id: "5814", number: 1),
                    DeckEntity(id: "1288", number: 1),
                    DeckEntity(id: "1044", number: 1),
                    DeckEntity(id: "873", number: 1),
                    DeckEntity(id: "823", number: 1),
                    DeckEntity(id: "717", number: 1),
                    DeckEntity(id: "663", number: 1),
                    DeckEntity(id: "504", number: 1),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "339", number: 1),
                    DeckEntity(id: "281", number: 1),
                    DeckEntity(id: "272", number: 1),
                    DeckEntity(id: "220", number: 1),
                    DeckEntity(id: "172", number: 1),
                    DeckEntity(id: "127", number: 1),
                    DeckEntity(id: "39", number: 1),
                    DeckEntity(id: "38", number: 1),
                    DeckEntity(id: "35", number: 1),
                    DeckEntity(id: "29", number: 1),
                    DeckEntity(id: "28", number: 1),
                    DeckEntity(id: "26", number: 1),
                    DeckEntity(id: "1896", number: 1),
                    DeckEntity(id: "1496", number: 1),
                    DeckEntity(id: "1358", number: 1),
                    DeckEntity(id: "1280", number: 1),
                    DeckEntity(id: "676", number: 1),
                    DeckEntity(id: "633", number: 1),
                    DeckEntity(id: "625", number: 1),
                    DeckEntity(id: "96", number: 1)
        ]]),
    DeckViewEntity(id: "limit1",
                   title: "2018年4月OCG限制卡",
                   introduction: "2018年4月OCG限制卡，一套卡组里仅能放一张",
                   deckEntitys: ["0": [
                    DeckEntity(id: "8379", number: 1),
                    DeckEntity(id: "8378", number: 1),
                    DeckEntity(id: "8282", number: 1),
                    DeckEntity(id: "8227", number: 1),
                    DeckEntity(id: "8153", number: 1),
                    DeckEntity(id: "8150", number: 1),
                    DeckEntity(id: "8140", number: 1),
                    DeckEntity(id: "8094", number: 1),
                    DeckEntity(id: "8056", number: 1),
                    DeckEntity(id: "7970", number: 1),
                    DeckEntity(id: "7880", number: 1),
                    DeckEntity(id: "7876", number: 1),
                    DeckEntity(id: "7790", number: 1),
                    DeckEntity(id: "7748", number: 1),
                    DeckEntity(id: "7301", number: 1),
                    DeckEntity(id: "7273", number: 1),
                    DeckEntity(id: "7181", number: 1),
                    DeckEntity(id: "7006", number: 1),
                    DeckEntity(id: "6732", number: 1),
                    DeckEntity(id: "6730", number: 1),
                    DeckEntity(id: "6709", number: 1),
                    DeckEntity(id: "6566", number: 1),
                    DeckEntity(id: "6524", number: 1),
                    DeckEntity(id: "6424", number: 1),
                    DeckEntity(id: "6423", number: 1),
                    DeckEntity(id: "4969", number: 1),
                    DeckEntity(id: "4710", number: 1),
                    DeckEntity(id: "4701", number: 1),
                    DeckEntity(id: "4181", number: 1),
                    DeckEntity(id: "4158", number: 1),
                    DeckEntity(id: "3656", number: 1),
                    DeckEntity(id: "3471", number: 1),
                    DeckEntity(id: "3160", number: 1),
                    DeckEntity(id: "2987", number: 1),
                    DeckEntity(id: "2964", number: 1),
                    DeckEntity(id: "2942", number: 1),
                    DeckEntity(id: "2441", number: 1),
                    DeckEntity(id: "2076", number: 1),
                    DeckEntity(id: "1949", number: 1),
                    DeckEntity(id: "1914", number: 1),
                    DeckEntity(id: "1322", number: 1),
                    DeckEntity(id: "520", number: 1),
                    DeckEntity(id: "515", number: 1),
                    DeckEntity(id: "226", number: 1),
                    DeckEntity(id: "225", number: 1),
                    DeckEntity(id: "224", number: 1),
                    DeckEntity(id: "223", number: 1),
                    DeckEntity(id: "222", number: 1),
                    DeckEntity(id: "8370", number: 1),
                    DeckEntity(id: "8301", number: 1),
                    DeckEntity(id: "7591", number: 1),
                    DeckEntity(id: "7390", number: 1),
                    DeckEntity(id: "7183", number: 1),
                    DeckEntity(id: "6808", number: 1),
                    DeckEntity(id: "6567", number: 1),
                    DeckEntity(id: "6510", number: 1),
                    DeckEntity(id: "5041", number: 1),
                    DeckEntity(id: "4629", number: 1),
                    DeckEntity(id: "4247", number: 1),
                    DeckEntity(id: "3666", number: 1),
                    DeckEntity(id: "3264", number: 1),
                    DeckEntity(id: "3014", number: 1),
                    DeckEntity(id: "1830", number: 1),
                    DeckEntity(id: "1296", number: 1),
                    DeckEntity(id: "1283", number: 1),
                    DeckEntity(id: "1149", number: 1),
                    DeckEntity(id: "990", number: 1),
                    DeckEntity(id: "715", number: 1),
                    DeckEntity(id: "708", number: 1),
                    DeckEntity(id: "569", number: 1),
                    DeckEntity(id: "283", number: 1),
                    DeckEntity(id: "219", number: 1),
                    DeckEntity(id: "8307", number: 1),
                    DeckEntity(id: "8200", number: 1),
                    DeckEntity(id: "4490", number: 1),
                    DeckEntity(id: "1690", number: 1),
                    DeckEntity(id: "1171", number: 1),
                    DeckEntity(id: "122", number: 1),
                    DeckEntity(id: "119", number: 1)
        ]]),
    DeckViewEntity(id: "limit2",
                   title: "2018年4月OCG准限制卡",
                   introduction: "2018年4月OCG准限制卡，一套卡组里仅能放两张",
                   deckEntitys: ["0": [
                    DeckEntity(id: "8167", number: 1),
                    DeckEntity(id: "8050", number: 1),
                    DeckEntity(id: "7963", number: 1),
                    DeckEntity(id: "6726", number: 1),
                    DeckEntity(id: "6519", number: 1),
                    DeckEntity(id: "4949", number: 1),
                    DeckEntity(id: "2105", number: 1),
                    DeckEntity(id: "8195", number: 1),
                    DeckEntity(id: "8185", number: 1),
                    DeckEntity(id: "7744", number: 1),
                    DeckEntity(id: "7456", number: 1),
                    DeckEntity(id: "3820", number: 1),
                    DeckEntity(id: "2049", number: 1),
                    DeckEntity(id: "1226", number: 1),
                    DeckEntity(id: "7408", number: 1),
                    DeckEntity(id: "4363", number: 1),
                    DeckEntity(id: "463", number: 1)
        ]]),
    DeckViewEntity(id: "2011",
                   title: "2011年第9届冠军",
                   introduction: "使用时间：2011年8月13日-14日 使用地点：荷兰阿姆斯特丹 使用者：Takashi Ogawa（アーサー） 所属国家地区：日本 卡组类型：【代行天使】",
                   deckEntitys: ["0": [
                    DeckEntity(id: "3621", number: 2),
                    DeckEntity(id: "4696", number: 3),
                    DeckEntity(id: "1069", number: 3),
                    DeckEntity(id: "3071", number: 1),
                    DeckEntity(id: "4697", number: 3),
                    DeckEntity(id: "416", number: 1),
                    DeckEntity(id: "1065", number: 3),
                    DeckEntity(id: "3434", number: 3),
                    DeckEntity(id: "4348", number: 3),
                    DeckEntity(id: "4699", number: 3),
                    DeckEntity(id: "171", number: 1),
                    DeckEntity(id: "38", number: 1),
                    DeckEntity(id: "37", number: 2),
                    DeckEntity(id: "219", number: 1),
                    DeckEntity(id: "662", number: 1),
                    DeckEntity(id: "463", number: 1),
                    DeckEntity(id: "4363", number: 2),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "626", number: 1),
                    DeckEntity(id: "100", number: 2),
                    DeckEntity(id: "676", number: 1)
        ]]),
    DeckViewEntity(id: "2010",
                   title: "2010年第8届冠军",
                   introduction: "使用时间：2010年8月14日-15日 使用地点：美国长滩 使用者：Galileo De Obaldia 所属国：巴拿马 卡组类型：【青蛙OTK】",
                   deckEntitys: ["0": [
                    DeckEntity(id: "1662", number: 2),
                    DeckEntity(id: "1813", number: 1),
                    DeckEntity(id: "3919", number: 3),
                    DeckEntity(id: "3509", number: 3),
                    DeckEntity(id: "3099", number: 3),
                    DeckEntity(id: "3098", number: 3),
                    DeckEntity(id: "3508", number: 3),
                    DeckEntity(id: "4232", number: 2),
                    DeckEntity(id: "3785", number: 1),
                    DeckEntity(id: "1812", number: 2),
                    DeckEntity(id: "1664", number: 3),
                    DeckEntity(id: "3943", number: 3),
                    DeckEntity(id: "1296", number: 1),
                    DeckEntity(id: "2943", number: 3),
                    DeckEntity(id: "1046", number: 3),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "38", number: 1),
                    DeckEntity(id: "823", number: 1),
                    DeckEntity(id: "3666", number: 1)
        ]]),
    DeckViewEntity(id: "2009",
                   title: "2009年第7届冠军",
                   introduction: "使用时间：2009年8月8日-9日 使用地点：日本东京 使用者：Benjamin Tan Hong Hwee 所属国家地区：新加坡 卡组类型：【BF】",
                   deckEntitys: ["0": [
                    DeckEntity(id: "2987", number: 1),
                    DeckEntity(id: "3490", number: 3),
                    DeckEntity(id: "3632", number: 3),
                    DeckEntity(id: "3489", number: 3),
                    DeckEntity(id: "3633", number: 3),
                    DeckEntity(id: "3488", number: 3),
                    DeckEntity(id: "3631", number: 1),
                    DeckEntity(id: "3672", number: 3),
                    DeckEntity(id: "3156", number: 2),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "38", number: 1),
                    DeckEntity(id: "37", number: 1),
                    DeckEntity(id: "1572", number: 1),
                    DeckEntity(id: "1610", number: 1),
                    DeckEntity(id: "219", number: 1),
                    DeckEntity(id: "463", number: 3),
                    DeckEntity(id: "1902", number: 3),
                    DeckEntity(id: "626", number: 2),
                    DeckEntity(id: "474", number: 1),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "1053", number: 2),
                    DeckEntity(id: "676", number: 1)
        ]]),
    DeckViewEntity(id: "2008",
                   title: "2008年第6届冠军",
                   introduction: "使用时间：2008年8月9日-10日 使用地点：德国柏林 使用者：Mutsuoka Kazuki(グリフィス） 所属国家地区：日本 卡组类型：【剑斗兽】",
                   deckEntitys: ["0": [
                    DeckEntity(id: "2230", number: 2),
                    DeckEntity(id: "2969", number: 1),
                    DeckEntity(id: "2850", number: 2),
                    DeckEntity(id: "3049", number: 2),
                    DeckEntity(id: "2999", number: 1),
                    DeckEntity(id: "2849", number: 1),
                    DeckEntity(id: "2848", number: 1),
                    DeckEntity(id: "2851", number: 1),
                    DeckEntity(id: "703", number: 1),
                    DeckEntity(id: "2146", number: 3),
                    DeckEntity(id: "3029", number: 3),
                    DeckEntity(id: "569", number: 1),
                    DeckEntity(id: "1536", number: 1),
                    DeckEntity(id: "1043", number: 1),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "37", number: 1),
                    DeckEntity(id: "219", number: 1),
                    DeckEntity(id: "127", number: 1),
                    DeckEntity(id: "662", number: 2),
                    DeckEntity(id: "463", number: 3),
                    DeckEntity(id: "1470", number: 2),
                    DeckEntity(id: "474", number: 1),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "626", number: 3),
                    DeckEntity(id: "2953", number: 1),
                    DeckEntity(id: "676", number: 1)
        ]]),
    DeckViewEntity(id: "2007",
                   title: "2007年第5届冠军",
                   introduction: "使用时间：2007年7月28-29日 使用地点：美国圣迭戈 使用者：Andres Toro 所属国家地区：智利 卡组类型：【帝Control】",
                   deckEntitys: ["0": [
                    DeckEntity(id: "6416", number: 3),
                    DeckEntity(id: "6317", number: 3),
                    DeckEntity(id: "2230", number: 1),
                    DeckEntity(id: "1452", number: 3),
                    DeckEntity(id: "686", number: 3),
                    DeckEntity(id: "416", number: 1),
                    DeckEntity(id: "703", number: 1),
                    DeckEntity(id: "2086", number: 3),
                    DeckEntity(id: "1812", number: 1),
                    DeckEntity(id: "124", number: 1),
                    DeckEntity(id: "1295", number: 1),
                    DeckEntity(id: "1730", number: 1),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "37", number: 1),
                    DeckEntity(id: "127", number: 1),
                    DeckEntity(id: "26", number: 1),
                    DeckEntity(id: "1610", number: 2),
                    DeckEntity(id: "28", number: 1),
                    DeckEntity(id: "1226", number: 1),
                    DeckEntity(id: "1461", number: 1),
                    DeckEntity(id: "662", number: 1),
                    DeckEntity(id: "474", number: 1),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "1171", number: 1),
                    DeckEntity(id: "101", number: 1),
                    DeckEntity(id: "676", number: 2)
        ]]),
    DeckViewEntity(id: "2006",
                   title: "2006年第4届冠军",
                   introduction: "使用时间：2006年8月5日-6日 使用地点：日本东京 使用者：Dario Longo 所属国家地区：意大利 卡组类型:【遗言混沌】",
                   deckEntitys: ["0": [
                    DeckEntity(id: "1084", number: 1),
                    DeckEntity(id: "971", number: 2),
                    DeckEntity(id: "2230", number: 2),
                    DeckEntity(id: "607", number: 2),
                    DeckEntity(id: "806", number: 1),
                    DeckEntity(id: "868", number: 1),
                    DeckEntity(id: "79", number: 2),
                    DeckEntity(id: "917", number: 1),
                    DeckEntity(id: "565", number: 1),
                    DeckEntity(id: "416", number: 1),
                    DeckEntity(id: "1370", number: 1),
                    DeckEntity(id: "515", number: 1),
                    DeckEntity(id: "703", number: 2),
                    DeckEntity(id: "260", number: 2),
                    DeckEntity(id: "504", number: 1),
                    DeckEntity(id: "569", number: 1),
                    DeckEntity(id: "1043", number: 1),
                    DeckEntity(id: "124", number: 2),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "37", number: 1),
                    DeckEntity(id: "26", number: 1),
                    DeckEntity(id: "615", number: 2),
                    DeckEntity(id: "1098", number: 2),
                    DeckEntity(id: "28", number: 1),
                    DeckEntity(id: "662", number: 1),
                    DeckEntity(id: "1288", number: 1),
                    DeckEntity(id: "1226", number: 1),
                    DeckEntity(id: "474", number: 1),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "524", number: 2)
        ]]),
    DeckViewEntity(id: "2005",
                   title: "2005年第3届冠军",
                   introduction: "使用时间：2005年8月7日 使用地点：日本东京 使用者：Markou Miltiadis 所属国家地区：希腊 卡组类型：【变异混沌凤凰神】",
                   deckEntitys: ["0": [
                    DeckEntity(id: "895", number: 1),
                    DeckEntity(id: "1501", number: 1),
                    DeckEntity(id: "91", number: 1),
                    DeckEntity(id: "366", number: 1),
                    DeckEntity(id: "607", number: 1),
                    DeckEntity(id: "1133", number: 1),
                    DeckEntity(id: "806", number: 1),
                    DeckEntity(id: "811", number: 1),
                    DeckEntity(id: "868", number: 1),
                    DeckEntity(id: "917", number: 1),
                    DeckEntity(id: "416", number: 1),
                    DeckEntity(id: "520", number: 1),
                    DeckEntity(id: "1502", number: 1),
                    DeckEntity(id: "801", number: 1),
                    DeckEntity(id: "260", number: 2),
                    DeckEntity(id: "1158", number: 1),
                    DeckEntity(id: "220", number: 1),
                    DeckEntity(id: "504", number: 1),
                    DeckEntity(id: "124", number: 1),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "37", number: 1),
                    DeckEntity(id: "127", number: 1),
                    DeckEntity(id: "26", number: 1),
                    DeckEntity(id: "1610", number: 1),
                    DeckEntity(id: "1098", number: 1),
                    DeckEntity(id: "29", number: 1),
                    DeckEntity(id: "662", number: 2),
                    DeckEntity(id: "207", number: 1),
                    DeckEntity(id: "717", number: 2),
                    DeckEntity(id: "1226", number: 2),
                    DeckEntity(id: "524", number: 1),
                    DeckEntity(id: "1171", number: 1),
                    DeckEntity(id: "101", number: 1),
                    DeckEntity(id: "474", number: 1),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "626", number: 1)
        ]]),
    DeckViewEntity(id: "2004",
               title: "2004年第2届冠军",
               introduction: "使用时间：2004年7月25日 使用地点：美国洛杉矶 使用者：Togawa Masatoshi 所属国家地区：日本卡 组类型：【混沌Control】",
               deckEntitys: ["0": [
                DeckEntity(id: "1004", number: 1),
                DeckEntity(id: "973", number: 1),
                DeckEntity(id: "91", number: 1),
                DeckEntity(id: "366", number: 2),
                DeckEntity(id: "806", number: 1),
                DeckEntity(id: "811", number: 1),
                DeckEntity(id: "868", number: 3),
                DeckEntity(id: "73", number: 1),
                DeckEntity(id: "454", number: 1),
                DeckEntity(id: "416", number: 1),
                DeckEntity(id: "260", number: 1),
                DeckEntity(id: "808", number: 1),
                DeckEntity(id: "1158", number: 1),
                DeckEntity(id: "220", number: 1),
                DeckEntity(id: "504", number: 1),
                DeckEntity(id: "663", number: 1),
                DeckEntity(id: "171", number: 1),
                DeckEntity(id: "1043", number: 1),
                DeckEntity(id: "124", number: 1),
                DeckEntity(id: "478", number: 1),
                DeckEntity(id: "37", number: 3),
                DeckEntity(id: "26", number: 1),
                DeckEntity(id: "615", number: 1),
                DeckEntity(id: "219", number: 1),
                DeckEntity(id: "127", number: 1),
                DeckEntity(id: "28", number: 1),
                DeckEntity(id: "35", number: 1),
                DeckEntity(id: "1226", number: 2),
                DeckEntity(id: "474", number: 1),
                DeckEntity(id: "335", number: 2),
                DeckEntity(id: "1171", number: 1),
                DeckEntity(id: "101", number: 1)
        ]]),
    DeckViewEntity(id: "2003",
               title: "2003年第1届冠军",
               introduction: "使用时间：2003年8月10日 使用地点：美国纽约 使用者：Ng Yu Leung 所属国家地区：中国香港 卡组类型：【手札破坏】",
               deckEntitys: ["0": [
                DeckEntity(id: "91", number: 1),
                DeckEntity(id: "498", number: 3),
                DeckEntity(id: "366", number: 1),
                DeckEntity(id: "657", number: 2),
                DeckEntity(id: "79", number: 3),
                DeckEntity(id: "454", number: 1),
                DeckEntity(id: "416", number: 1),
                DeckEntity(id: "590", number: 1),
                DeckEntity(id: "260", number: 1),
                DeckEntity(id: "1158", number: 1),
                DeckEntity(id: "601", number: 1),
                DeckEntity(id: "220", number: 1),
                DeckEntity(id: "504", number: 1),
                DeckEntity(id: "663", number: 1),
                DeckEntity(id: "172", number: 1),
                DeckEntity(id: "171", number: 1),
                DeckEntity(id: "124", number: 1),
                DeckEntity(id: "1149", number: 1),
                DeckEntity(id: "478", number: 1),
                DeckEntity(id: "37", number: 3),
                DeckEntity(id: "272", number: 1),
                DeckEntity(id: "26", number: 1),
                DeckEntity(id: "219", number: 1),
                DeckEntity(id: "127", number: 1),
                DeckEntity(id: "28", number: 1),
                DeckEntity(id: "35", number: 1),
                DeckEntity(id: "29", number: 1),
                DeckEntity(id: "122", number: 1),
                DeckEntity(id: "474", number: 1),
                DeckEntity(id: "1171", number: 1),
                DeckEntity(id: "101", number: 1),
                DeckEntity(id: "631", number: 3)
        ]])

]
