//
//  DeckViewEntityConstant.swift
//  yugioh
//
//  Created by Aaron on 9/8/2017.
//  Copyright © 2017 sightcorner. All rights reserved.
//

import Foundation



var deckViewEntitysConstant: [DeckViewEntity] = [
    DeckViewEntity(id: "0", title: "我的卡组", introduction: "我的卡组", deckEntitys: []),
    DeckViewEntity(id: "2011",
                   title: "2011年第9届冠军",
                   introduction: "使用时间：2011年8月13日-14日 使用地点：荷兰阿姆斯特丹 使用者：Takashi Ogawa（アーサー） 所属国家地区：日本 卡组类型：【代行天使】",
                   deckEntitys: [
                    DeckEntity(id: "3621", number: 2),
                    DeckEntity(id: "4696", number: 3),
                    DeckEntity(id: "1069", number: 3),
                    DeckEntity(id: "3071", number: 1),
                    DeckEntity(id: "4697", number: 3),
                    DeckEntity(id: "416", number: 1),
                    DeckEntity(id: "1065", number: 3),
                    DeckEntity(id: "3434", number: 3),
                    DeckEntity(id: "4348", number: 3),
                    DeckEntity(id: "4699", number: 3),
                    DeckEntity(id: "171", number: 1),
                    DeckEntity(id: "38", number: 1),
                    DeckEntity(id: "37", number: 2),
                    DeckEntity(id: "219", number: 1),
                    DeckEntity(id: "662", number: 1),
                    DeckEntity(id: "463", number: 1),
                    DeckEntity(id: "4363", number: 2),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "626", number: 1),
                    DeckEntity(id: "100", number: 2),
                    DeckEntity(id: "676", number: 1)
        ]),
    DeckViewEntity(id: "2010",
                   title: "2010年第8届冠军",
                   introduction: "使用时间：2010年8月14日-15日 使用地点：美国长滩 使用者：Galileo De Obaldia 所属国：巴拿马 卡组类型：【青蛙OTK】",
                   deckEntitys: [
                    DeckEntity(id: "1662", number: 2),
                    DeckEntity(id: "1813", number: 1),
                    DeckEntity(id: "3919", number: 3),
                    DeckEntity(id: "3509", number: 3),
                    DeckEntity(id: "3099", number: 3),
                    DeckEntity(id: "3098", number: 3),
                    DeckEntity(id: "3508", number: 3),
                    DeckEntity(id: "4232", number: 2),
                    DeckEntity(id: "3785", number: 1),
                    DeckEntity(id: "1812", number: 2),
                    DeckEntity(id: "1664", number: 3),
                    DeckEntity(id: "3943", number: 3),
                    DeckEntity(id: "1296", number: 1),
                    DeckEntity(id: "2943", number: 3),
                    DeckEntity(id: "1046", number: 3),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "38", number: 1),
                    DeckEntity(id: "823", number: 1),
                    DeckEntity(id: "3666", number: 1)
        ]),
    DeckViewEntity(id: "2009",
                   title: "2009年第7届冠军",
                   introduction: "使用时间：2009年8月8日-9日 使用地点：日本东京 使用者：Benjamin Tan Hong Hwee 所属国家地区：新加坡 卡组类型：【BF】",
                   deckEntitys: [
                    DeckEntity(id: "2987", number: 1),
                    DeckEntity(id: "3490", number: 3),
                    DeckEntity(id: "3632", number: 3),
                    DeckEntity(id: "3489", number: 3),
                    DeckEntity(id: "3633", number: 3),
                    DeckEntity(id: "3488", number: 3),
                    DeckEntity(id: "3631", number: 1),
                    DeckEntity(id: "3672", number: 3),
                    DeckEntity(id: "3156", number: 2),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "38", number: 1),
                    DeckEntity(id: "37", number: 1),
                    DeckEntity(id: "1572", number: 1),
                    DeckEntity(id: "1610", number: 1),
                    DeckEntity(id: "219", number: 1),
                    DeckEntity(id: "463", number: 3),
                    DeckEntity(id: "1902", number: 3),
                    DeckEntity(id: "626", number: 2),
                    DeckEntity(id: "474", number: 1),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "1053", number: 2),
                    DeckEntity(id: "676", number: 1)
        ]),
    DeckViewEntity(id: "2008",
                   title: "2008年第6届冠军",
                   introduction: "使用时间：2008年8月9日-10日 使用地点：德国柏林 使用者：Mutsuoka Kazuki(グリフィス） 所属国家地区：日本 卡组类型：【剑斗兽】",
                   deckEntitys: [
                    DeckEntity(id: "2230", number: 2),
                    DeckEntity(id: "2969", number: 1),
                    DeckEntity(id: "2850", number: 2),
                    DeckEntity(id: "3049", number: 2),
                    DeckEntity(id: "2999", number: 1),
                    DeckEntity(id: "2849", number: 1),
                    DeckEntity(id: "2848", number: 1),
                    DeckEntity(id: "2851", number: 1),
                    DeckEntity(id: "703", number: 1),
                    DeckEntity(id: "2146", number: 3),
                    DeckEntity(id: "3029", number: 3),
                    DeckEntity(id: "569", number: 1),
                    DeckEntity(id: "1536", number: 1),
                    DeckEntity(id: "1043", number: 1),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "37", number: 1),
                    DeckEntity(id: "219", number: 1),
                    DeckEntity(id: "127", number: 1),
                    DeckEntity(id: "662", number: 2),
                    DeckEntity(id: "463", number: 3),
                    DeckEntity(id: "1470", number: 2),
                    DeckEntity(id: "474", number: 1),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "626", number: 3),
                    DeckEntity(id: "2953", number: 1),
                    DeckEntity(id: "676", number: 1)
        ]),
    DeckViewEntity(id: "2007",
                   title: "2007年第5届冠军",
                   introduction: "使用时间：2007年7月28-29日 使用地点：美国圣迭戈 使用者：Andres Toro 所属国家地区：智利 卡组类型：【帝Control】",
                   deckEntitys: [
                    DeckEntity(id: "6416", number: 3),
                    DeckEntity(id: "6317", number: 3),
                    DeckEntity(id: "2230", number: 1),
                    DeckEntity(id: "1452", number: 3),
                    DeckEntity(id: "686", number: 3),
                    DeckEntity(id: "416", number: 1),
                    DeckEntity(id: "703", number: 1),
                    DeckEntity(id: "2086", number: 3),
                    DeckEntity(id: "1812", number: 1),
                    DeckEntity(id: "124", number: 1),
                    DeckEntity(id: "1295", number: 1),
                    DeckEntity(id: "1730", number: 1),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "37", number: 1),
                    DeckEntity(id: "127", number: 1),
                    DeckEntity(id: "26", number: 1),
                    DeckEntity(id: "1610", number: 2),
                    DeckEntity(id: "28", number: 1),
                    DeckEntity(id: "1226", number: 1),
                    DeckEntity(id: "1461", number: 1),
                    DeckEntity(id: "662", number: 1),
                    DeckEntity(id: "474", number: 1),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "1171", number: 1),
                    DeckEntity(id: "101", number: 1),
                    DeckEntity(id: "676", number: 2)
        ]),
    DeckViewEntity(id: "2006",
                   title: "2006年第4届冠军",
                   introduction: "使用时间：2006年8月5日-6日 使用地点：日本东京 使用者：Dario Longo 所属国家地区：意大利 卡组类型:【遗言混沌】",
                   deckEntitys: [
                    DeckEntity(id: "1084", number: 1),
                    DeckEntity(id: "971", number: 2),
                    DeckEntity(id: "2230", number: 2),
                    DeckEntity(id: "607", number: 2),
                    DeckEntity(id: "806", number: 1),
                    DeckEntity(id: "868", number: 1),
                    DeckEntity(id: "79", number: 2),
                    DeckEntity(id: "917", number: 1),
                    DeckEntity(id: "565", number: 1),
                    DeckEntity(id: "416", number: 1),
                    DeckEntity(id: "1370", number: 1),
                    DeckEntity(id: "515", number: 1),
                    DeckEntity(id: "703", number: 2),
                    DeckEntity(id: "260", number: 2),
                    DeckEntity(id: "504", number: 1),
                    DeckEntity(id: "569", number: 1),
                    DeckEntity(id: "1043", number: 1),
                    DeckEntity(id: "124", number: 2),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "37", number: 1),
                    DeckEntity(id: "26", number: 1),
                    DeckEntity(id: "615", number: 2),
                    DeckEntity(id: "1098", number: 2),
                    DeckEntity(id: "28", number: 1),
                    DeckEntity(id: "662", number: 1),
                    DeckEntity(id: "1288", number: 1),
                    DeckEntity(id: "1226", number: 1),
                    DeckEntity(id: "474", number: 1),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "524", number: 2)
        ]),
    DeckViewEntity(id: "2005",
                   title: "2005年第3届冠军",
                   introduction: "使用时间：2005年8月7日 使用地点：日本东京 使用者：Markou Miltiadis 所属国家地区：希腊 卡组类型：【变异混沌凤凰神】",
                   deckEntitys: [
                    DeckEntity(id: "895", number: 1),
                    DeckEntity(id: "1501", number: 1),
                    DeckEntity(id: "91", number: 1),
                    DeckEntity(id: "366", number: 1),
                    DeckEntity(id: "607", number: 1),
                    DeckEntity(id: "1133", number: 1),
                    DeckEntity(id: "806", number: 1),
                    DeckEntity(id: "811", number: 1),
                    DeckEntity(id: "868", number: 1),
                    DeckEntity(id: "917", number: 1),
                    DeckEntity(id: "416", number: 1),
                    DeckEntity(id: "520", number: 1),
                    DeckEntity(id: "1502", number: 1),
                    DeckEntity(id: "801", number: 1),
                    DeckEntity(id: "260", number: 2),
                    DeckEntity(id: "1158", number: 1),
                    DeckEntity(id: "220", number: 1),
                    DeckEntity(id: "504", number: 1),
                    DeckEntity(id: "124", number: 1),
                    DeckEntity(id: "478", number: 1),
                    DeckEntity(id: "37", number: 1),
                    DeckEntity(id: "127", number: 1),
                    DeckEntity(id: "26", number: 1),
                    DeckEntity(id: "1610", number: 1),
                    DeckEntity(id: "1098", number: 1),
                    DeckEntity(id: "29", number: 1),
                    DeckEntity(id: "662", number: 2),
                    DeckEntity(id: "207", number: 1),
                    DeckEntity(id: "717", number: 2),
                    DeckEntity(id: "1226", number: 2),
                    DeckEntity(id: "524", number: 1),
                    DeckEntity(id: "1171", number: 1),
                    DeckEntity(id: "101", number: 1),
                    DeckEntity(id: "474", number: 1),
                    DeckEntity(id: "335", number: 1),
                    DeckEntity(id: "626", number: 1)
        ]),
    DeckViewEntity(id: "2004",
               title: "2004年第2届冠军",
               introduction: "使用时间：2004年7月25日 使用地点：美国洛杉矶 使用者：Togawa Masatoshi 所属国家地区：日本卡 组类型：【混沌Control】",
               deckEntitys: [
                DeckEntity(id: "1004", number: 1),
                DeckEntity(id: "973", number: 1),
                DeckEntity(id: "91", number: 1),
                DeckEntity(id: "366", number: 2),
                DeckEntity(id: "806", number: 1),
                DeckEntity(id: "811", number: 1),
                DeckEntity(id: "868", number: 3),
                DeckEntity(id: "73", number: 1),
                DeckEntity(id: "454", number: 1),
                DeckEntity(id: "416", number: 1),
                DeckEntity(id: "260", number: 1),
                DeckEntity(id: "808", number: 1),
                DeckEntity(id: "1158", number: 1),
                DeckEntity(id: "220", number: 1),
                DeckEntity(id: "504", number: 1),
                DeckEntity(id: "663", number: 1),
                DeckEntity(id: "171", number: 1),
                DeckEntity(id: "1043", number: 1),
                DeckEntity(id: "124", number: 1),
                DeckEntity(id: "478", number: 1),
                DeckEntity(id: "37", number: 3),
                DeckEntity(id: "26", number: 1),
                DeckEntity(id: "615", number: 1),
                DeckEntity(id: "219", number: 1),
                DeckEntity(id: "127", number: 1),
                DeckEntity(id: "28", number: 1),
                DeckEntity(id: "35", number: 1),
                DeckEntity(id: "1226", number: 2),
                DeckEntity(id: "474", number: 1),
                DeckEntity(id: "335", number: 2),
                DeckEntity(id: "1171", number: 1),
                DeckEntity(id: "101", number: 1)
        ]),
    DeckViewEntity(id: "2003",
               title: "2003年第1届冠军",
               introduction: "使用时间：2003年8月10日 使用地点：美国纽约 使用者：Ng Yu Leung 所属国家地区：中国香港 卡组类型：【手札破坏】",
               deckEntitys: [
                DeckEntity(id: "91", number: 1),
                DeckEntity(id: "498", number: 3),
                DeckEntity(id: "366", number: 1),
                DeckEntity(id: "657", number: 2),
                DeckEntity(id: "79", number: 3),
                DeckEntity(id: "454", number: 1),
                DeckEntity(id: "416", number: 1),
                DeckEntity(id: "590", number: 1),
                DeckEntity(id: "260", number: 1),
                DeckEntity(id: "1158", number: 1),
                DeckEntity(id: "601", number: 1),
                DeckEntity(id: "220", number: 1),
                DeckEntity(id: "504", number: 1),
                DeckEntity(id: "663", number: 1),
                DeckEntity(id: "172", number: 1),
                DeckEntity(id: "171", number: 1),
                DeckEntity(id: "124", number: 1),
                DeckEntity(id: "1149", number: 1),
                DeckEntity(id: "478", number: 1),
                DeckEntity(id: "37", number: 3),
                DeckEntity(id: "272", number: 1),
                DeckEntity(id: "26", number: 1),
                DeckEntity(id: "219", number: 1),
                DeckEntity(id: "127", number: 1),
                DeckEntity(id: "28", number: 1),
                DeckEntity(id: "35", number: 1),
                DeckEntity(id: "29", number: 1),
                DeckEntity(id: "122", number: 1),
                DeckEntity(id: "474", number: 1),
                DeckEntity(id: "1171", number: 1),
                DeckEntity(id: "101", number: 1),
                DeckEntity(id: "631", number: 3)
        ])

]
